[package]
name = "av"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
common = { workspace = true }
dcl = { workspace = true }
dcl_component = { workspace = true }
ipfs = { workspace = true }
scene_runner = { workspace = true }
comms = { workspace = true }

bevy = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
isahc = { workspace = true }
urlencoding = { workspace = true }
futures-lite = { workspace = true }
bevy_kira_audio = { workspace = true }
kira = { workspace = true }

cpal = "0.15.2"
ffmpeg-next = "6.0.0"
thiserror = "1.0"