[package]
name = "console"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
common = { workspace = true }

bevy = { workspace = true }
bevy_console = { workspace = true }
clap = { workspace = true }
